//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pts.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.ProviderSettings = new HashSet<ProviderSetting>();
            this.Profiles = new HashSet<Profile>();
            this.PaymentTokens = new HashSet<PaymentToken>();
        }
    
        public int ProviderID { get; set; }
        public string ProviderName { get; set; }
        public int ProviderTypeID { get; set; }
    
        public virtual ProviderType ProviderType { get; set; }
        public virtual ICollection<ProviderSetting> ProviderSettings { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<PaymentToken> PaymentTokens { get; set; }
    }
}
